FROM node:alpine
WORKDIR /app
COPY package*.json .
RUN npm i
COPY . .

ENV PORT=4000
EXPOSE ${PORT}

ENV POSTGRES_USERNAME=${POSTGRES_USER}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ENV POSTGRES_DB=${POSTGRES_DB}
ENV POSTGRES_PORT=${POSTGRES_PORT}
ENV TZ=${TIMEZONE}


CMD [ "npm","start" ]