version: '3'

services:
  db:
    container_name: db_postgres
    image: postgres:15-alpine
    build: ./src/DataBase
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  nestjs:
    container_name: rest-service
    build: ./
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped
