version: '3'

services:
  db:
    build: ./src/DataBase
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  nestjs:
    depends_on:
      - db
    image: image-rest
    build: .
    ports:
      - ${PORT}:${PORT}

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
