version: '3'

services:
  db:
    container_name: database
    image: postgres:15-alpine
    build: ./src/DataBase
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - rest_bridge

  nestjs:
    container_name: backend
    image: nestjs_app
    build: ./
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped
    networks:
      - rest_bridge

networks:
  rest_bridge:
    driver: bridge
    # external: true
